name: "Deploy to NuGet"

on:
  push:
    branches:
      - master
    # tags:
      # - 'v*'

env:
  PROJECT_PATH: 'src/HsNsH.NuGet.Work.Core/HsNsH.NuGet.Work.Core.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/hsnsh/index.json'

jobs:
  deploy:
    name: 'Deploy Release JOB'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: 'Restore Dependencies'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build Project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2

      - name: 'Pack Package'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}